In [172]:
import pandas as pd

In [173]:
def clean_column_names(df):
    """
    Function Description:
    Standardises column names by converting them to lowercase, removing extra spaces, replacing spaces/hyphens with underscores, and renaming the police data month column to date.

    Input:
    df (DataFrame): Raw dataframe with original column names.

    Output:
    df (DataFrame): Dataframe with standardised column names.
    """
#cleaning column names
    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )
#renaming month column to date
    df = df.rename(
        columns={
            "month": "date"
        }
    )

    return df

In [174]:
def clean_dates(df):
    """
    Function Description:
    Converts the date column into datetime format and creates extra date fields for year, month number, and month name.

    Input:
    df (DataFrame): Dataframe containing a date column.

    Output:
    df (DataFrame): Dataframe with year, month_num, and month_name columns added.
    """
#changing date column to date format
    df["date"] = pd.to_datetime(df["date"])
    
#creates a year column
    df["year"] = df["date"].dt.year

#creates month number column
    df["month_num"] = df["date"].dt.month

#creates month name column
    df["month_name"] = df["date"].dt.month_name()

    return df

In [175]:
def add_force_name(df, force_name):
    """
    Function Description:
    Adds a police force name to the dataframe so records can be grouped and merged by force.

    Input:
    df (DataFrame): Dataframe to update.
    force_name (str): Name of the police force.

    Output:
    df (DataFrame): Dataframe with police_force column added.
    """

    df["police_force"] = force_name

    return df

In [176]:
def select_required_columns(df):
    """
    Function Description:
    Keeps only the columns needed for analysis and removes unnecessary columns to reduce dataset size.

    Input:
    df (DataFrame): Raw or cleaned crime dataframe.

    Output:
    df (DataFrame): Dataframe containing only required columns that exist in the input.
    """

#columns we want
    required_columns = [
        "date",
        "crime_type",
        "longitude",
        "latitude"
    ]

    existing_columns = [
        col for col in required_columns
        if col in df.columns
    ]

    df = df[existing_columns]

    return df

In [177]:
def print_size_change(dataset_name, original_df, final_df):
    """
    Function Description:
    Prints a validation summary comparing the number of rows before and after cleaning.

    Input:
    dataset_name (str): Name/path of the dataset being processed.
    original_df (DataFrame): Dataframe before cleaning.
    final_df (DataFrame): Dataframe after cleaning.

    Output:
    None: Prints original row count, final row count, and rows removed.
    """
    original_rows = len(original_df)
    final_rows = len(final_df)
    removed_rows = original_rows - final_rows

    print(f"\n{dataset_name}")
    print(f"Original rows: {original_rows}")
    print(f"Final rows: {final_rows}")
    print(f"Rows removed: {removed_rows}")

In [178]:
def process_crime_file(file_path, force_name):
    """
    Function Description:
    Imports and cleans one crime CSV file using the project cleaning functions.

    Input:
    file_path (str): Path to the crime CSV file.
    force_name (str): Name of the police force linked to the file.

    Output:
    df (DataFrame): Cleaned crime dataframe for one file.
    """

#importing csv
    df = pd.read_csv(
        file_path,
        low_memory=False
    )
    
    original_df = df.copy()
    
#cleaning data
    df = clean_column_names(df)

    df= select_required_columns(df)

    df = clean_dates(df)

    #df = filter_crime_types(df)

    df = add_force_name(
        df,
        force_name
    )
    
    print_size_change(
    file_path,
    original_df,
    df
    )

    return df

In [179]:
def process_crime_files(crime_files):
    """
    Function Description:
    Processes multiple crime CSV files and combines them into one cleaned dataframe.

    Input:
    crime_files (list): List of tuples containing file paths and police force names.

    Output:
    combined_df (DataFrame): Combined cleaned crime dataframe.
    """

    cleaned_files = []

    for file_path, force_name in crime_files:

        cleaned_df = process_crime_file(
            file_path,
            force_name
        )

        cleaned_files.append(cleaned_df)

#combining all the cleaned crime month dataframes into year dataframes
    combined_df = pd.concat(
        cleaned_files,
        ignore_index=True
    )

    return combined_df

In [180]:
#crime data for 2019
crime_files_2019 = [
    ("2019-04-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-04-merseyside-street.csv", "Merseyside Police"),
    ("2019-04-west-midlands-street.csv", "West Midlands Police"),
    ("2019-04-northumbria-street.csv", "Northumbria Police"),
    ("2019-05-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-05-merseyside-street.csv", "Merseyside Police"),
    ("2019-05-west-midlands-street.csv", "West Midlands Police"),
    ("2019-05-northumbria-street.csv", "Northumbria Police"),
    ("2019-06-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-06-merseyside-street.csv", "Merseyside Police"),
    ("2019-06-west-midlands-street.csv", "West Midlands Police"),
    ("2019-06-northumbria-street.csv", "Northumbria Police"),
    ("2019-07-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-07-merseyside-street.csv", "Merseyside Police"),
    ("2019-07-west-midlands-street.csv", "West Midlands Police"),
    ("2019-07-northumbria-street.csv", "Northumbria Police"),
    ("2019-08-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-08-merseyside-street.csv", "Merseyside Police"),
    ("2019-08-west-midlands-street.csv", "West Midlands Police"),
    ("2019-08-northumbria-street.csv", "Northumbria Police"),
    ("2019-09-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-09-merseyside-street.csv", "Merseyside Police"),
    ("2019-09-west-midlands-street.csv", "West Midlands Police"),
    ("2019-09-northumbria-street.csv", "Northumbria Police"),
    ("2019-10-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-10-merseyside-street.csv", "Merseyside Police"),
    ("2019-10-west-midlands-street.csv", "West Midlands Police"),
    ("2019-10-northumbria-street.csv", "Northumbria Police"),
    ("2019-11-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-11-merseyside-street.csv", "Merseyside Police"),
    ("2019-11-west-midlands-street.csv", "West Midlands Police"),
    ("2019-11-northumbria-street.csv", "Northumbria Police"),
    ("2019-12-metropolitan-street.csv", "Metropolitan Police"),
    ("2019-12-merseyside-street.csv", "Merseyside Police"),
    ("2019-12-west-midlands-street.csv", "West Midlands Police"),
    ("2019-12-northumbria-street.csv", "Northumbria Police"),
]

In [181]:
#crime data for 2020
crime_files_2020 = [
    ("2020-01-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-01-merseyside-street.csv", "Merseyside Police"),
    ("2020-01-west-midlands-street.csv", "West Midlands Police"),
    ("2020-01-northumbria-street.csv", "Northumbria Police"),
    ("2020-02-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-02-merseyside-street.csv", "Merseyside Police"),
    ("2020-02-west-midlands-street.csv", "West Midlands Police"),
    ("2020-02-northumbria-street.csv", "Northumbria Police"),
    ("2020-03-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-03-merseyside-street.csv", "Merseyside Police"),
    ("2020-03-west-midlands-street.csv", "West Midlands Police"),
    ("2020-03-northumbria-street.csv", "Northumbria Police"),    
    ("2020-04-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-04-merseyside-street.csv", "Merseyside Police"),
    ("2020-04-west-midlands-street.csv", "West Midlands Police"),
    ("2020-04-northumbria-street.csv", "Northumbria Police"),
    ("2020-05-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-05-merseyside-street.csv", "Merseyside Police"),
    ("2020-05-west-midlands-street.csv", "West Midlands Police"),
    ("2020-05-northumbria-street.csv", "Northumbria Police"),
    ("2020-06-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-06-merseyside-street.csv", "Merseyside Police"),
    ("2020-06-west-midlands-street.csv", "West Midlands Police"),
    ("2020-06-northumbria-street.csv", "Northumbria Police"),
    ("2020-07-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-07-merseyside-street.csv", "Merseyside Police"),
    ("2020-07-west-midlands-street.csv", "West Midlands Police"),
    ("2020-07-northumbria-street.csv", "Northumbria Police"),
    ("2020-08-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-08-merseyside-street.csv", "Merseyside Police"),
    ("2020-08-west-midlands-street.csv", "West Midlands Police"),
    ("2020-08-northumbria-street.csv", "Northumbria Police"),
    ("2020-09-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-09-merseyside-street.csv", "Merseyside Police"),
    ("2020-09-west-midlands-street.csv", "West Midlands Police"),
    ("2020-09-northumbria-street.csv", "Northumbria Police"),
    ("2020-10-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-10-merseyside-street.csv", "Merseyside Police"),
    ("2020-10-west-midlands-street.csv", "West Midlands Police"),
    ("2020-10-northumbria-street.csv", "Northumbria Police"),
    ("2020-11-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-11-merseyside-street.csv", "Merseyside Police"),
    ("2020-11-west-midlands-street.csv", "West Midlands Police"),
    ("2020-11-northumbria-street.csv", "Northumbria Police"),
    ("2020-12-metropolitan-street.csv", "Metropolitan Police"),
    ("2020-12-merseyside-street.csv", "Merseyside Police"),
    ("2020-12-west-midlands-street.csv", "West Midlands Police"),
    ("2020-12-northumbria-street.csv", "Northumbria Police"),
]

In [182]:
#crime data for 2021
crime_files_2021 = [
    ("2021-01-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-01-merseyside-street.csv", "Merseyside Police"),
    ("2021-01-west-midlands-street.csv", "West Midlands Police"),
    ("2021-01-northumbria-street.csv", "Northumbria Police"),
    ("2021-02-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-02-merseyside-street.csv", "Merseyside Police"),
    ("2021-02-west-midlands-street.csv", "West Midlands Police"),
    ("2021-02-northumbria-street.csv", "Northumbria Police"),
    ("2021-03-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-03-merseyside-street.csv", "Merseyside Police"),
    ("2021-03-west-midlands-street.csv", "West Midlands Police"),
    ("2021-03-northumbria-street.csv", "Northumbria Police"),    
    ("2021-04-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-04-merseyside-street.csv", "Merseyside Police"),
    ("2021-04-west-midlands-street.csv", "West Midlands Police"),
    ("2021-04-northumbria-street.csv", "Northumbria Police"),
    ("2021-05-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-05-merseyside-street.csv", "Merseyside Police"),
    ("2021-05-west-midlands-street.csv", "West Midlands Police"),
    ("2021-05-northumbria-street.csv", "Northumbria Police"),
    ("2021-06-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-06-merseyside-street.csv", "Merseyside Police"),
    ("2021-06-west-midlands-street.csv", "West Midlands Police"),
    ("2021-06-northumbria-street.csv", "Northumbria Police"),
    ("2021-07-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-07-merseyside-street.csv", "Merseyside Police"),
    ("2021-07-west-midlands-street.csv", "West Midlands Police"),
    ("2021-07-northumbria-street.csv", "Northumbria Police"),
    ("2021-08-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-08-merseyside-street.csv", "Merseyside Police"),
    ("2021-08-west-midlands-street.csv", "West Midlands Police"),
    ("2021-08-northumbria-street.csv", "Northumbria Police"),
    ("2021-09-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-09-merseyside-street.csv", "Merseyside Police"),
    ("2021-09-west-midlands-street.csv", "West Midlands Police"),
    ("2021-09-northumbria-street.csv", "Northumbria Police"),
    ("2021-10-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-10-merseyside-street.csv", "Merseyside Police"),
    ("2021-10-west-midlands-street.csv", "West Midlands Police"),
    ("2021-10-northumbria-street.csv", "Northumbria Police"),
    ("2021-11-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-11-merseyside-street.csv", "Merseyside Police"),
    ("2021-11-west-midlands-street.csv", "West Midlands Police"),
    ("2021-11-northumbria-street.csv", "Northumbria Police"),
    ("2021-12-metropolitan-street.csv", "Metropolitan Police"),
    ("2021-12-merseyside-street.csv", "Merseyside Police"),
    ("2021-12-west-midlands-street.csv", "West Midlands Police"),
    ("2021-12-northumbria-street.csv", "Northumbria Police"),
]

In [183]:
#crime data for 2022
#2022-03-west-midlands-street did not exist in the database
crime_files_2022 = [
    ("2022-01-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-01-merseyside-street.csv", "Merseyside Police"),
    ("2022-01-west-midlands-street.csv", "West Midlands Police"),
    ("2022-01-northumbria-street.csv", "Northumbria Police"),
    ("2022-02-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-02-merseyside-street.csv", "Merseyside Police"),
    ("2022-02-west-midlands-street.csv", "West Midlands Police"),
    ("2022-02-northumbria-street.csv", "Northumbria Police"),
    ("2022-03-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-03-merseyside-street.csv", "Merseyside Police"),
    ("2022-03-northumbria-street.csv", "Northumbria Police"),    
    ("2022-04-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-04-merseyside-street.csv", "Merseyside Police"),
    ("2022-04-west-midlands-street.csv", "West Midlands Police"),
    ("2022-04-northumbria-street.csv", "Northumbria Police"),
    ("2022-05-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-05-merseyside-street.csv", "Merseyside Police"),
    ("2022-05-west-midlands-street.csv", "West Midlands Police"),
    ("2022-05-northumbria-street.csv", "Northumbria Police"),
    ("2022-06-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-06-merseyside-street.csv", "Merseyside Police"),
    ("2022-06-west-midlands-street.csv", "West Midlands Police"),
    ("2022-06-northumbria-street.csv", "Northumbria Police"),
    ("2022-07-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-07-merseyside-street.csv", "Merseyside Police"),
    ("2022-07-west-midlands-street.csv", "West Midlands Police"),
    ("2022-07-northumbria-street.csv", "Northumbria Police"),
    ("2022-08-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-08-merseyside-street.csv", "Merseyside Police"),
    ("2022-08-west-midlands-street.csv", "West Midlands Police"),
    ("2022-08-northumbria-street.csv", "Northumbria Police"),
    ("2022-09-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-09-merseyside-street.csv", "Merseyside Police"),
    ("2022-09-west-midlands-street.csv", "West Midlands Police"),
    ("2022-09-northumbria-street.csv", "Northumbria Police"),
    ("2022-10-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-10-merseyside-street.csv", "Merseyside Police"),
    ("2022-10-west-midlands-street.csv", "West Midlands Police"),
    ("2022-10-northumbria-street.csv", "Northumbria Police"),
    ("2022-11-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-11-merseyside-street.csv", "Merseyside Police"),
    ("2022-11-west-midlands-street.csv", "West Midlands Police"),
    ("2022-11-northumbria-street.csv", "Northumbria Police"),
    ("2022-12-metropolitan-street.csv", "Metropolitan Police"),
    ("2022-12-merseyside-street.csv", "Merseyside Police"),
    ("2022-12-west-midlands-street.csv", "West Midlands Police"),
    ("2022-12-northumbria-street.csv", "Northumbria Police"),
]

In [184]:
#crime data for 2023
crime_files_2023 = [
    ("2023-01-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-01-merseyside-street.csv", "Merseyside Police"),
    ("2023-01-west-midlands-street.csv", "West Midlands Police"),
    ("2023-01-northumbria-street.csv", "Northumbria Police"),
    ("2023-02-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-02-merseyside-street.csv", "Merseyside Police"),
    ("2023-02-west-midlands-street.csv", "West Midlands Police"),
    ("2023-02-northumbria-street.csv", "Northumbria Police"),
    ("2023-03-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-03-merseyside-street.csv", "Merseyside Police"),
    ("2023-03-west-midlands-street.csv", "West Midlands Police"),
    ("2023-03-northumbria-street.csv", "Northumbria Police"),    
    ("2023-04-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-04-merseyside-street.csv", "Merseyside Police"),
    ("2023-04-west-midlands-street.csv", "West Midlands Police"),
    ("2023-04-northumbria-street.csv", "Northumbria Police"),
    ("2023-05-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-05-merseyside-street.csv", "Merseyside Police"),
    ("2023-05-west-midlands-street.csv", "West Midlands Police"),
    ("2023-05-northumbria-street.csv", "Northumbria Police"),
    ("2023-06-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-06-merseyside-street.csv", "Merseyside Police"),
    ("2023-06-west-midlands-street.csv", "West Midlands Police"),
    ("2023-06-northumbria-street.csv", "Northumbria Police"),
    ("2023-07-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-07-merseyside-street.csv", "Merseyside Police"),
    ("2023-07-west-midlands-street.csv", "West Midlands Police"),
    ("2023-07-northumbria-street.csv", "Northumbria Police"),
    ("2023-08-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-08-merseyside-street.csv", "Merseyside Police"),
    ("2023-08-west-midlands-street.csv", "West Midlands Police"),
    ("2023-08-northumbria-street.csv", "Northumbria Police"),
    ("2023-09-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-09-merseyside-street.csv", "Merseyside Police"),
    ("2023-09-west-midlands-street.csv", "West Midlands Police"),
    ("2023-09-northumbria-street.csv", "Northumbria Police"),
    ("2023-10-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-10-merseyside-street.csv", "Merseyside Police"),
    ("2023-10-west-midlands-street.csv", "West Midlands Police"),
    ("2023-10-northumbria-street.csv", "Northumbria Police"),
    ("2023-11-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-11-merseyside-street.csv", "Merseyside Police"),
    ("2023-11-west-midlands-street.csv", "West Midlands Police"),
    ("2023-11-northumbria-street.csv", "Northumbria Police"),
    ("2023-12-metropolitan-street.csv", "Metropolitan Police"),
    ("2023-12-merseyside-street.csv", "Merseyside Police"),
    ("2023-12-west-midlands-street.csv", "West Midlands Police"),
    ("2023-12-northumbria-street.csv", "Northumbria Police"),
]

In [185]:
#crime data for 2024
crime_files_2024 = [
    ("2024-01-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-01-merseyside-street.csv", "Merseyside Police"),
    ("2024-01-west-midlands-street.csv", "West Midlands Police"),
    ("2024-01-northumbria-street.csv", "Northumbria Police"),
    ("2024-02-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-02-merseyside-street.csv", "Merseyside Police"),
    ("2024-02-west-midlands-street.csv", "West Midlands Police"),
    ("2024-02-northumbria-street.csv", "Northumbria Police"),
    ("2024-03-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-03-merseyside-street.csv", "Merseyside Police"),
    ("2024-03-west-midlands-street.csv", "West Midlands Police"),
    ("2024-03-northumbria-street.csv", "Northumbria Police"),    
    ("2024-04-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-04-merseyside-street.csv", "Merseyside Police"),
    ("2024-04-west-midlands-street.csv", "West Midlands Police"),
    ("2024-04-northumbria-street.csv", "Northumbria Police"),
    ("2024-05-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-05-merseyside-street.csv", "Merseyside Police"),
    ("2024-05-west-midlands-street.csv", "West Midlands Police"),
    ("2024-05-northumbria-street.csv", "Northumbria Police"),
    ("2024-06-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-06-merseyside-street.csv", "Merseyside Police"),
    ("2024-06-west-midlands-street.csv", "West Midlands Police"),
    ("2024-06-northumbria-street.csv", "Northumbria Police"),
    ("2024-07-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-07-merseyside-street.csv", "Merseyside Police"),
    ("2024-07-west-midlands-street.csv", "West Midlands Police"),
    ("2024-07-northumbria-street.csv", "Northumbria Police"),
    ("2024-08-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-08-merseyside-street.csv", "Merseyside Police"),
    ("2024-08-west-midlands-street.csv", "West Midlands Police"),
    ("2024-08-northumbria-street.csv", "Northumbria Police"),
    ("2024-09-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-09-merseyside-street.csv", "Merseyside Police"),
    ("2024-09-west-midlands-street.csv", "West Midlands Police"),
    ("2024-09-northumbria-street.csv", "Northumbria Police"),
    ("2024-10-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-10-merseyside-street.csv", "Merseyside Police"),
    ("2024-10-west-midlands-street.csv", "West Midlands Police"),
    ("2024-10-northumbria-street.csv", "Northumbria Police"),
    ("2024-11-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-11-merseyside-street.csv", "Merseyside Police"),
    ("2024-11-west-midlands-street.csv", "West Midlands Police"),
    ("2024-11-northumbria-street.csv", "Northumbria Police"),
    ("2024-12-metropolitan-street.csv", "Metropolitan Police"),
    ("2024-12-merseyside-street.csv", "Merseyside Police"),
    ("2024-12-west-midlands-street.csv", "West Midlands Police"),
    ("2024-12-northumbria-street.csv", "Northumbria Police"),
]

In [186]:
#crime data for 2025
crime_files_2025 = [
    ("2025-01-metropolitan-street.csv", "Metropolitan Police"),
    ("2025-01-merseyside-street.csv", "Merseyside Police"),
    ("2025-01-west-midlands-street.csv", "West Midlands Police"),
    ("2025-01-northumbria-street.csv", "Northumbria Police"),
    ("2025-02-metropolitan-street.csv", "Metropolitan Police"),
    ("2025-02-merseyside-street.csv", "Merseyside Police"),
    ("2025-02-west-midlands-street.csv", "West Midlands Police"),
    ("2025-02-northumbria-street.csv", "Northumbria Police"),
    ("2025-03-metropolitan-street.csv", "Metropolitan Police"),
    ("2025-03-merseyside-street.csv", "Merseyside Police"),
    ("2025-03-west-midlands-street.csv", "West Midlands Police"),
    ("2025-03-northumbria-street.csv", "Northumbria Police"),    
]

In [187]:
#takes a bit of time
#processes each month in each year using the functions above
processed_crime_2019= process_crime_files(crime_files_2019)
processed_crime_2020= process_crime_files(crime_files_2020)
processed_crime_2021= process_crime_files(crime_files_2021)
processed_crime_2022= process_crime_files(crime_files_2022)
processed_crime_2023= process_crime_files(crime_files_2023)
processed_crime_2024= process_crime_files(crime_files_2024)
processed_crime_2025= process_crime_files(crime_files_2025)

2019-04-metropolitan-street.csv
Original rows: 91858
Final rows: 91858
Rows removed: 0

2019-04-merseyside-street.csv
Original rows: 13224
Final rows: 13224
Rows removed: 0

2019-04-west-midlands-street.csv
Original rows: 24370
Final rows: 24370
Rows removed: 0

2019-04-northumbria-street.csv
Original rows: 16991
Final rows: 16991
Rows removed: 0

2019-05-metropolitan-street.csv
Original rows: 96143
Final rows: 96143
Rows removed: 0

2019-05-merseyside-street.csv
Original rows: 13820
Final rows: 13820
Rows removed: 0

2019-05-west-midlands-street.csv
Original rows: 24808
Final rows: 24808
Rows removed: 0

2019-05-northumbria-street.csv
Original rows: 17370
Final rows: 17370
Rows removed: 0

2019-06-metropolitan-street.csv
Original rows: 95942
Final rows: 95942
Rows removed: 0

2019-06-merseyside-street.csv
Original rows: 13297
Final rows: 13297
Rows removed: 0

2019-06-west-midlands-street.csv
Original rows: 24657
Final rows: 24657
Rows removed: 0

2019-06-northumbria-street.csv
Original rows: 16955
Final rows: 16955
Rows removed: 0

2019-07-metropolitan-street.csv
Original rows: 99329
Final rows: 99329
Rows removed: 0

2019-07-merseyside-street.csv
Original rows: 14534
Final rows: 14534
Rows removed: 0

2019-07-west-midlands-street.csv
Original rows: 26535
Final rows: 26535
Rows removed: 0

2019-07-northumbria-street.csv
Original rows: 18252
Final rows: 18252
Rows removed: 0

2019-08-metropolitan-street.csv
Original rows: 91534
Final rows: 91534
Rows removed: 0

2019-08-merseyside-street.csv
Original rows: 14405
Final rows: 14405
Rows removed: 0

2019-08-west-midlands-street.csv
Original rows: 24580
Final rows: 24580
Rows removed: 0

2019-08-northumbria-street.csv
Original rows: 17047
Final rows: 17047
Rows removed: 0

2019-09-metropolitan-street.csv
Original rows: 87342
Final rows: 87342
Rows removed: 0

2019-09-merseyside-street.csv
Original rows: 13350
Final rows: 13350
Rows removed: 0

2019-09-west-midlands-street.csv
Original rows: 23518
Final rows: 23518
Rows removed: 0

2019-09-northumbria-street.csv
Original rows: 16486
Final rows: 16486
Rows removed: 0

2019-10-metropolitan-street.csv
Original rows: 96516
Final rows: 96516
Rows removed: 0

2019-10-merseyside-street.csv
Original rows: 15523
Final rows: 15523
Rows removed: 0

2019-10-west-midlands-street.csv
Original rows: 25115
Final rows: 25115
Rows removed: 0

2019-10-northumbria-street.csv
Original rows: 16982
Final rows: 16982
Rows removed: 0

2019-11-metropolitan-street.csv
Original rows: 91204
Final rows: 91204
Rows removed: 0

2019-11-merseyside-street.csv
Original rows: 14060
Final rows: 14060
Rows removed: 0

2019-11-west-midlands-street.csv
Original rows: 23931
Final rows: 23931
Rows removed: 0

2019-11-northumbria-street.csv
Original rows: 15339
Final rows: 15339
Rows removed: 0

2019-12-metropolitan-street.csv
Original rows: 86075
Final rows: 86075
Rows removed: 0

2019-12-merseyside-street.csv
Original rows: 12743
Final rows: 12743
Rows removed: 0

2019-12-west-midlands-street.csv
Original rows: 24110
Final rows: 24110
Rows removed: 0

2019-12-northumbria-street.csv
Original rows: 12645
Final rows: 12645
Rows removed: 0

2020-01-metropolitan-street.csv
Original rows: 90979
Final rows: 90979
Rows removed: 0

2020-01-merseyside-street.csv
Original rows: 13534
Final rows: 13534
Rows removed: 0

2020-01-west-midlands-street.csv
Original rows: 25643
Final rows: 25643
Rows removed: 0

2020-01-northumbria-street.csv
Original rows: 16082
Final rows: 16082
Rows removed: 0

2020-02-metropolitan-street.csv
Original rows: 86984
Final rows: 86984
Rows removed: 0

2020-02-merseyside-street.csv
Original rows: 13195
Final rows: 13195
Rows removed: 0

2020-02-west-midlands-street.csv
Original rows: 23382
Final rows: 23382
Rows removed: 0

2020-02-northumbria-street.csv
Original rows: 15190
Final rows: 15190
Rows removed: 0

2020-03-metropolitan-street.csv
Original rows: 87409
Final rows: 87409
Rows removed: 0

2020-03-merseyside-street.csv
Original rows: 13735
Final rows: 13735
Rows removed: 0

2020-03-west-midlands-street.csv
Original rows: 23400
Final rows: 23400
Rows removed: 0

2020-03-northumbria-street.csv
Original rows: 15422
Final rows: 15422
Rows removed: 0

2020-04-metropolitan-street.csv
Original rows: 109951
Final rows: 109951
Rows removed: 0

2020-04-merseyside-street.csv
Original rows: 13650
Final rows: 13650
Rows removed: 0

2020-04-west-midlands-street.csv
Original rows: 23752
Final rows: 23752
Rows removed: 0

2020-04-northumbria-street.csv
Original rows: 18049
Final rows: 18049
Rows removed: 0

2020-05-metropolitan-street.csv
Original rows: 114008
Final rows: 114008
Rows removed: 0

2020-05-merseyside-street.csv
Original rows: 14811
Final rows: 14811
Rows removed: 0

2020-05-west-midlands-street.csv
Original rows: 26210
Final rows: 26210
Rows removed: 0

2020-05-northumbria-street.csv
Original rows: 19344
Final rows: 19344
Rows removed: 0

2020-06-metropolitan-street.csv
Original rows: 100198
Final rows: 100198
Rows removed: 0

2020-06-merseyside-street.csv
Original rows: 14684
Final rows: 14684
Rows removed: 0

2020-06-west-midlands-street.csv
Original rows: 25566
Final rows: 25566
Rows removed: 0

2020-06-northumbria-street.csv
Original rows: 17118
Final rows: 17118
Rows removed: 0

2020-07-metropolitan-street.csv
Original rows: 103657
Final rows: 103657
Rows removed: 0

2020-07-merseyside-street.csv
Original rows: 14980
Final rows: 14980
Rows removed: 0

2020-07-west-midlands-street.csv
Original rows: 27750
Final rows: 27750
Rows removed: 0

2020-07-northumbria-street.csv
Original rows: 14055
Final rows: 14055
Rows removed: 0

2020-08-metropolitan-street.csv
Original rows: 104782
Final rows: 104782
Rows removed: 0

2020-08-merseyside-street.csv
Original rows: 15579
Final rows: 15579
Rows removed: 0

2020-08-west-midlands-street.csv
Original rows: 28451
Final rows: 28451
Rows removed: 0

2020-08-northumbria-street.csv
Original rows: 17819
Final rows: 17819
Rows removed: 0

2020-09-metropolitan-street.csv
Original rows: 99633
Final rows: 99633
Rows removed: 0

2020-09-merseyside-street.csv
Original rows: 14885
Final rows: 14885
Rows removed: 0

2020-09-west-midlands-street.csv
Original rows: 28175
Final rows: 28175
Rows removed: 0

2020-09-northumbria-street.csv
Original rows: 17325
Final rows: 17325
Rows removed: 0

2020-10-metropolitan-street.csv
Original rows: 99471
Final rows: 99471
Rows removed: 0

2020-10-merseyside-street.csv
Original rows: 16252
Final rows: 16252
Rows removed: 0

2020-10-west-midlands-street.csv
Original rows: 29910
Final rows: 29910
Rows removed: 0

2020-10-northumbria-street.csv
Original rows: 18028
Final rows: 18028
Rows removed: 0

2020-11-metropolitan-street.csv
Original rows: 96914
Final rows: 96914
Rows removed: 0

2020-11-merseyside-street.csv
Original rows: 14621
Final rows: 14621
Rows removed: 0

2020-11-west-midlands-street.csv
Original rows: 30608
Final rows: 30608
Rows removed: 0

2020-11-northumbria-street.csv
Original rows: 17061
Final rows: 17061
Rows removed: 0

2020-12-metropolitan-street.csv
Original rows: 87936
Final rows: 87936
Rows removed: 0

2020-12-merseyside-street.csv
Original rows: 13511
Final rows: 13511
Rows removed: 0

2020-12-west-midlands-street.csv
Original rows: 29950
Final rows: 29950
Rows removed: 0

2020-12-northumbria-street.csv
Original rows: 14658
Final rows: 14658
Rows removed: 0

2021-01-metropolitan-street.csv
Original rows: 84848
Final rows: 84848
Rows removed: 0

2021-01-merseyside-street.csv
Original rows: 13053
Final rows: 13053
Rows removed: 0

2021-01-west-midlands-street.csv
Original rows: 29117
Final rows: 29117
Rows removed: 0

2021-01-northumbria-street.csv
Original rows: 14994
Final rows: 14994
Rows removed: 0

2021-02-metropolitan-street.csv
Original rows: 79974
Final rows: 79974
Rows removed: 0

2021-02-merseyside-street.csv
Original rows: 13059
Final rows: 13059
Rows removed: 0

2021-02-west-midlands-street.csv
Original rows: 27575
Final rows: 27575
Rows removed: 0

2021-02-northumbria-street.csv
Original rows: 14476
Final rows: 14476
Rows removed: 0

2021-03-metropolitan-street.csv
Original rows: 91666
Final rows: 91666
Rows removed: 0

2021-03-merseyside-street.csv
Original rows: 15657
Final rows: 15657
Rows removed: 0

2021-03-west-midlands-street.csv
Original rows: 32115
Final rows: 32115
Rows removed: 0

2021-03-northumbria-street.csv
Original rows: 18151
Final rows: 18151
Rows removed: 0

2021-04-metropolitan-street.csv
Original rows: 87199
Final rows: 87199
Rows removed: 0

2021-04-merseyside-street.csv
Original rows: 14994
Final rows: 14994
Rows removed: 0

2021-04-west-midlands-street.csv
Original rows: 29969
Final rows: 29969
Rows removed: 0

2021-04-northumbria-street.csv
Original rows: 17241
Final rows: 17241
Rows removed: 0

2021-05-metropolitan-street.csv
Original rows: 92225
Final rows: 92225
Rows removed: 0

2021-05-merseyside-street.csv
Original rows: 15516
Final rows: 15516
Rows removed: 0

2021-05-west-midlands-street.csv
Original rows: 31923
Final rows: 31923
Rows removed: 0

2021-05-northumbria-street.csv
Original rows: 16828
Final rows: 16828
Rows removed: 0

2021-06-metropolitan-street.csv
Original rows: 95527
Final rows: 95527
Rows removed: 0

2021-06-merseyside-street.csv
Original rows: 16378
Final rows: 16378
Rows removed: 0

2021-06-west-midlands-street.csv
Original rows: 33535
Final rows: 33535
Rows removed: 0

2021-06-northumbria-street.csv
Original rows: 17110
Final rows: 17110
Rows removed: 0

2021-07-metropolitan-street.csv
Original rows: 94605
Final rows: 94605
Rows removed: 0

2021-07-merseyside-street.csv
Original rows: 17091
Final rows: 17091
Rows removed: 0

2021-07-west-midlands-street.csv
Original rows: 34608
Final rows: 34608
Rows removed: 0

2021-07-northumbria-street.csv
Original rows: 15228
Final rows: 15228
Rows removed: 0

2021-08-metropolitan-street.csv
Original rows: 89240
Final rows: 89240
Rows removed: 0

2021-08-merseyside-street.csv
Original rows: 15568
Final rows: 15568
Rows removed: 0

2021-08-west-midlands-street.csv
Original rows: 32095
Final rows: 32095
Rows removed: 0

2021-08-northumbria-street.csv
Original rows: 15894
Final rows: 15894
Rows removed: 0

2021-09-metropolitan-street.csv
Original rows: 90881
Final rows: 90881
Rows removed: 0

2021-09-merseyside-street.csv
Original rows: 15901
Final rows: 15901
Rows removed: 0

2021-09-west-midlands-street.csv
Original rows: 32594
Final rows: 32594
Rows removed: 0

2021-09-northumbria-street.csv
Original rows: 14509
Final rows: 14509
Rows removed: 0

2021-10-metropolitan-street.csv
Original rows: 93992
Final rows: 93992
Rows removed: 0

2021-10-merseyside-street.csv
Original rows: 16600
Final rows: 16600
Rows removed: 0

2021-10-west-midlands-street.csv
Original rows: 32990
Final rows: 32990
Rows removed: 0

2021-10-northumbria-street.csv
Original rows: 15497
Final rows: 15497
Rows removed: 0

2021-11-metropolitan-street.csv
Original rows: 90141
Final rows: 90141
Rows removed: 0

2021-11-merseyside-street.csv
Original rows: 15875
Final rows: 15875
Rows removed: 0

2021-11-west-midlands-street.csv
Original rows: 33771
Final rows: 33771
Rows removed: 0

2021-11-northumbria-street.csv
Original rows: 14819
Final rows: 14819
Rows removed: 0

2021-12-metropolitan-street.csv
Original rows: 82578
Final rows: 82578
Rows removed: 0

2021-12-merseyside-street.csv
Original rows: 14018
Final rows: 14018
Rows removed: 0

2021-12-west-midlands-street.csv
Original rows: 32204
Final rows: 32204
Rows removed: 0

2021-12-northumbria-street.csv
Original rows: 13281
Final rows: 13281
Rows removed: 0

2022-01-metropolitan-street.csv
Original rows: 84368
Final rows: 84368
Rows removed: 0

2022-01-merseyside-street.csv
Original rows: 15029
Final rows: 15029
Rows removed: 0

2022-01-west-midlands-street.csv
Original rows: 31283
Final rows: 31283
Rows removed: 0

2022-01-northumbria-street.csv
Original rows: 14815
Final rows: 14815
Rows removed: 0

2022-02-metropolitan-street.csv
Original rows: 80278
Final rows: 80278
Rows removed: 0

2022-02-merseyside-street.csv
Original rows: 14164
Final rows: 14164
Rows removed: 0

2022-02-west-midlands-street.csv
Original rows: 29797
Final rows: 29797
Rows removed: 0

2022-02-northumbria-street.csv
Original rows: 14196
Final rows: 14196
Rows removed: 0

2022-03-metropolitan-street.csv
Original rows: 107792
Final rows: 107792
Rows removed: 0

2022-03-merseyside-street.csv
Original rows: 16476
Final rows: 16476
Rows removed: 0

2022-03-northumbria-street.csv
Original rows: 15871
Final rows: 15871
Rows removed: 0

2022-04-metropolitan-street.csv
Original rows: 85916
Final rows: 85916
Rows removed: 0

2022-04-merseyside-street.csv
Original rows: 15571
Final rows: 15571
Rows removed: 0

2022-04-west-midlands-street.csv
Original rows: 31843
Final rows: 31843
Rows removed: 0

2022-04-northumbria-street.csv
Original rows: 15658
Final rows: 15658
Rows removed: 0

2022-05-metropolitan-street.csv
Original rows: 95413
Final rows: 95413
Rows removed: 0

2022-05-merseyside-street.csv
Original rows: 17200
Final rows: 17200
Rows removed: 0

2022-05-west-midlands-street.csv
Original rows: 34105
Final rows: 34105
Rows removed: 0

2022-05-northumbria-street.csv
Original rows: 16522
Final rows: 16522
Rows removed: 0

2022-06-metropolitan-street.csv
Original rows: 92544
Final rows: 92544
Rows removed: 0

2022-06-merseyside-street.csv
Original rows: 15900
Final rows: 15900
Rows removed: 0

2022-06-west-midlands-street.csv
Original rows: 33334
Final rows: 33334
Rows removed: 0

2022-06-northumbria-street.csv
Original rows: 15362
Final rows: 15362
Rows removed: 0

2022-07-metropolitan-street.csv
Original rows: 96038
Final rows: 96038
Rows removed: 0

2022-07-merseyside-street.csv
Original rows: 15899
Final rows: 15899
Rows removed: 0

2022-07-west-midlands-street.csv
Original rows: 34582
Final rows: 34582
Rows removed: 0

2022-07-northumbria-street.csv
Original rows: 16495
Final rows: 16495
Rows removed: 0

2022-08-metropolitan-street.csv
Original rows: 93931
Final rows: 93931
Rows removed: 0

2022-08-merseyside-street.csv
Original rows: 16512
Final rows: 16512
Rows removed: 0

2022-08-west-midlands-street.csv
Original rows: 33675
Final rows: 33675
Rows removed: 0

2022-08-northumbria-street.csv
Original rows: 16572
Final rows: 16572
Rows removed: 0

2022-09-metropolitan-street.csv
Original rows: 85828
Final rows: 85828
Rows removed: 0

2022-09-merseyside-street.csv
Original rows: 15260
Final rows: 15260
Rows removed: 0

2022-09-west-midlands-street.csv
Original rows: 31697
Final rows: 31697
Rows removed: 0

2022-09-northumbria-street.csv
Original rows: 15247
Final rows: 15247
Rows removed: 0

2022-10-metropolitan-street.csv
Original rows: 111741
Final rows: 111741
Rows removed: 0

2022-10-merseyside-street.csv
Original rows: 15918
Final rows: 15918
Rows removed: 0

2022-10-west-midlands-street.csv
Original rows: 32958
Final rows: 32958
Rows removed: 0

2022-10-northumbria-street.csv
Original rows: 16428
Final rows: 16428
Rows removed: 0

2022-11-metropolitan-street.csv
Original rows: 89924
Final rows: 89924
Rows removed: 0

2022-11-merseyside-street.csv
Original rows: 15358
Final rows: 15358
Rows removed: 0

2022-11-west-midlands-street.csv
Original rows: 30964
Final rows: 30964
Rows removed: 0

2022-11-northumbria-street.csv
Original rows: 15038
Final rows: 15038
Rows removed: 0

2022-12-metropolitan-street.csv
Original rows: 82718
Final rows: 82718
Rows removed: 0

2022-12-merseyside-street.csv
Original rows: 13186
Final rows: 13186
Rows removed: 0

2022-12-west-midlands-street.csv
Original rows: 29343
Final rows: 29343
Rows removed: 0

2022-12-northumbria-street.csv
Original rows: 12949
Final rows: 12949
Rows removed: 0

2023-01-metropolitan-street.csv
Original rows: 87211
Final rows: 87211
Rows removed: 0

2023-01-merseyside-street.csv
Original rows: 14147
Final rows: 14147
Rows removed: 0

2023-01-west-midlands-street.csv
Original rows: 30937
Final rows: 30937
Rows removed: 0

2023-01-northumbria-street.csv
Original rows: 14513
Final rows: 14513
Rows removed: 0

2023-02-metropolitan-street.csv
Original rows: 83041
Final rows: 83041
Rows removed: 0

2023-02-merseyside-street.csv
Original rows: 14090
Final rows: 14090
Rows removed: 0

2023-02-west-midlands-street.csv
Original rows: 29477
Final rows: 29477
Rows removed: 0

2023-02-northumbria-street.csv
Original rows: 15621
Final rows: 15621
Rows removed: 0

2023-03-metropolitan-street.csv
Original rows: 92833
Final rows: 92833
Rows removed: 0

2023-03-merseyside-street.csv
Original rows: 14858
Final rows: 14858
Rows removed: 0

2023-03-west-midlands-street.csv
Original rows: 32452
Final rows: 32452
Rows removed: 0

2023-03-northumbria-street.csv
Original rows: 16585
Final rows: 16585
Rows removed: 0

2023-04-metropolitan-street.csv
Original rows: 87547
Final rows: 87547
Rows removed: 0

2023-04-merseyside-street.csv
Original rows: 14518
Final rows: 14518
Rows removed: 0

2023-04-west-midlands-street.csv
Original rows: 31289
Final rows: 31289
Rows removed: 0

2023-04-northumbria-street.csv
Original rows: 16388
Final rows: 16388
Rows removed: 0

2023-05-metropolitan-street.csv
Original rows: 96140
Final rows: 96140
Rows removed: 0

2023-05-merseyside-street.csv
Original rows: 15591
Final rows: 15591
Rows removed: 0

2023-05-west-midlands-street.csv
Original rows: 30589
Final rows: 30589
Rows removed: 0

2023-05-northumbria-street.csv
Original rows: 17686
Final rows: 17686
Rows removed: 0

2023-06-metropolitan-street.csv
Original rows: 105947
Final rows: 105947
Rows removed: 0

2023-06-merseyside-street.csv
Original rows: 15025
Final rows: 15025
Rows removed: 0

2023-06-west-midlands-street.csv
Original rows: 31521
Final rows: 31521
Rows removed: 0

2023-06-northumbria-street.csv
Original rows: 17178
Final rows: 17178
Rows removed: 0

2023-07-metropolitan-street.csv
Original rows: 99418
Final rows: 99418
Rows removed: 0

2023-07-merseyside-street.csv
Original rows: 13825
Final rows: 13825
Rows removed: 0

2023-07-west-midlands-street.csv
Original rows: 31601
Final rows: 31601
Rows removed: 0

2023-07-northumbria-street.csv
Original rows: 16140
Final rows: 16140
Rows removed: 0

2023-08-metropolitan-street.csv
Original rows: 94301
Final rows: 94301
Rows removed: 0

2023-08-merseyside-street.csv
Original rows: 13741
Final rows: 13741
Rows removed: 0

2023-08-west-midlands-street.csv
Original rows: 29958
Final rows: 29958
Rows removed: 0

2023-08-northumbria-street.csv
Original rows: 17119
Final rows: 17119
Rows removed: 0

2023-09-metropolitan-street.csv
Original rows: 96019
Final rows: 96019
Rows removed: 0

2023-09-merseyside-street.csv
Original rows: 13566
Final rows: 13566
Rows removed: 0

2023-09-west-midlands-street.csv
Original rows: 29671
Final rows: 29671
Rows removed: 0

2023-09-northumbria-street.csv
Original rows: 16596
Final rows: 16596
Rows removed: 0

2023-10-metropolitan-street.csv
Original rows: 102375
Final rows: 102375
Rows removed: 0

2023-10-merseyside-street.csv
Original rows: 13449
Final rows: 13449
Rows removed: 0

2023-10-west-midlands-street.csv
Original rows: 30836
Final rows: 30836
Rows removed: 0

2023-10-northumbria-street.csv
Original rows: 16296
Final rows: 16296
Rows removed: 0

2023-11-metropolitan-street.csv
Original rows: 96803
Final rows: 96803
Rows removed: 0

2023-11-merseyside-street.csv
Original rows: 12525
Final rows: 12525
Rows removed: 0

2023-11-west-midlands-street.csv
Original rows: 28269
Final rows: 28269
Rows removed: 0

2023-11-northumbria-street.csv
Original rows: 14721
Final rows: 14721
Rows removed: 0

2023-12-metropolitan-street.csv
Original rows: 93396
Final rows: 93396
Rows removed: 0

2023-12-merseyside-street.csv
Original rows: 11868
Final rows: 11868
Rows removed: 0

2023-12-west-midlands-street.csv
Original rows: 28058
Final rows: 28058
Rows removed: 0

2023-12-northumbria-street.csv
Original rows: 13419
Final rows: 13419
Rows removed: 0

2024-01-metropolitan-street.csv
Original rows: 91411
Final rows: 91411
Rows removed: 0

2024-01-merseyside-street.csv

In [188]:
def combine_cleaned_years(yearly_dfs):
    """
    Function Description:
    Combines cleaned yearly crime dataframes into one full crime dataset.

    Input:
    yearly_dfs (list): List of cleaned yearly dataframes.

    Output:
    combined_df (DataFrame): Combined dataframe containing all years.
    """
    combined_df = pd.concat(
        yearly_dfs,
        ignore_index=True
    )

    return combined_df

In [189]:
def aggregate_crime_monthly(df):
    """
    Function Description:
    Aggregates cleaned crime records to the reporting grain: police force, month, and crime type.

    Input:
    df (DataFrame): Cleaned crime dataframe at individual-record level.

    Output:
    crime_monthly (DataFrame): Monthly aggregated crime dataframe with crime_count.
    """
    crime_monthly = (
        df.groupby(
            [
                "police_force",
                "date",
                "year",
                "month_num",
                "month_name",
                "crime_type"
            ],
            as_index=False
        )
        .size()
        .rename(columns={"size": "crime_count"})
    )

    return crime_monthly

In [190]:
def validate_reporting_grain(df):
    """
    Function Description:
    Checks whether the crime reporting dataset has duplicate rows at the intended reporting grain.

    Input:
    df (DataFrame): Monthly aggregated crime dataframe.

    Output:
    None: Prints duplicate count and validation message.
    """
    duplicates = df.duplicated(
        subset=[
            "police_force",
            "date",
            "crime_type"
        ]
    ).sum()

    print("Duplicate reporting rows:", duplicates)

    if duplicates == 0:
        print("Reporting grain is valid.")
    else:
        print("There are duplicate rows.")

In [191]:
def check_missing_values(df):
    """
    Function Description:
    Checks and prints the number of missing values in each column.

    Input:
    df (DataFrame): Dataframe to validate.

    Output:
    missing_values (Series): Count of missing values by column.
    """
    missing_values = df.isna().sum()

    print(missing_values)

    return missing_values

In [192]:
def export_dataset(df, file_name):
    """
    Function Description:
    Exports a dataframe to CSV without the index.

    Input:
    df (DataFrame): Dataframe to export.
    file_name (str): Output CSV filename or path.

    Output:
    None: Exports CSV file and prints confirmation.
    """
    df.to_csv(
        file_name,
        index=False
    )

    print(f"Exported: {file_name}")

In [193]:
def create_monthly_crime_dataset(yearly_dfs, output_file):
    """
    Function Description:
    Runs the monthly crime dataset creation process by combining yearly data, aggregating, validating, checking missing values, and exporting.

    Input:
    yearly_dfs (list): List of cleaned yearly crime dataframes.
    output_file (str): Output CSV filename or path.

    Output:
    crime_monthly (DataFrame): Monthly aggregated crime dataset.
    """

#combines crime data that are in years into one dataframe
    crime_clean = combine_cleaned_years(yearly_dfs)

#aggregate data
    crime_monthly = aggregate_crime_monthly(crime_clean)

#validate data
    validate_reporting_grain(crime_monthly)

#check for missing values
    check_missing_values(crime_monthly)
    
#export the dataframe
    export_dataset(
        crime_monthly,
        output_file
    )

    return crime_monthly

In [194]:
#using functions above to create the final crime dataframe
crime_monthly = create_monthly_crime_dataset(
    [
        processed_crime_2019,
        processed_crime_2020,
        processed_crime_2021,
        processed_crime_2022,
        processed_crime_2023,
        processed_crime_2024,
        processed_crime_2025
    ],
    "crime_monthly_clean.csv"
)

Duplicate reporting rows: 0
Reporting grain is valid.
police_force    0
date            0
year            0
month_num       0
month_name      0
crime_type      0
crime_count     0
dtype: int64
Exported: crime_monthly_clean.csv

In [195]:
crime_monthly

,police_force,date,year,month_num,month_name,crime_type,crime_count
0,Merseyside Police,2019-04-01,2019,4,April,Anti-social behaviour,2534
1,Merseyside Police,2019-04-01,2019,4,April,Bicycle theft,136
2,Merseyside Police,2019-04-01,2019,4,April,Burglary,716
3,Merseyside Police,2019-04-01,2019,4,April,Criminal damage and arson,1289
4,Merseyside Police,2019-04-01,2019,4,April,Drugs,764
...,...,...,...,...,...,...,...
4013,West Midlands Police,2025-03-01,2025,3,March,Robbery,475
4014,West Midlands Police,2025-03-01,2025,3,March,Shoplifting,3003
4015,West Midlands Police,2025-03-01,2025,3,March,Theft from the person,201
4016,West Midlands Police,2025-03-01,2025,3,March,Vehicle crime,2213
4017,West Midlands Police,2025-03-01,2025,3,March,Violence and sexual offences,11263

In [196]:
#used to correlate the team to the police force
TEAM_FORCE_MAPPING = {
    "Arsenal": "Metropolitan Police",
    "Chelsea": "Metropolitan Police",
    "Tottenham": "Metropolitan Police",
    "West Ham": "Metropolitan Police",
    "Crystal Palace": "Metropolitan Police",

    "Liverpool": "Merseyside Police",
    "Everton": "Merseyside Police",

    "Aston Villa": "West Midlands Police",
    "Wolves": "West Midlands Police",

    "Newcastle": "Northumbria Police"
}

In [197]:
def clean_football_columns(df):
    """
    Function Description:
    Standardises football dataset column names.

    Input:
    df (DataFrame): Raw football dataframe.

    Output:
    df (DataFrame): Football dataframe with cleaned column names.
    """
    df = df.copy()

    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
    )

    return df

In [198]:
def select_football_columns(df):
    """
    Function Description:
    Keeps only the football columns required for the match-day enrichment analysis.

    Input:
    df (DataFrame): Raw football dataframe.

    Output:
    df (DataFrame): Reduced football dataframe containing required columns.
    """

#columns we need
    required_columns = [
        "date",
        "hometeam",
        "awayteam",
        "fthg",
        "ftag",
        "ftr"
    ]

    existing_columns = [
        col for col in required_columns
        if col in df.columns
    ]

    df = df[existing_columns]

    return df

In [199]:
def clean_football_dates(df):
    """
    Function Description:
    Converts football match dates and creates year, month number, and month name fields.

    Input:
    df (DataFrame): Football dataframe containing a date column.

    Output:
    df (DataFrame): Football dataframe with date fields added.
    """
    df = df.copy()

#formats date column to datetime
    df["date"] = pd.to_datetime(
        df["date"],
        dayfirst=True,
        errors="coerce"
    )

#creates year column
    df["year"] = df["date"].dt.year

#creates month number column
    df["month_num"] = df["date"].dt.month

#creates month name column
    df["month_name"] = df["date"].dt.month_name()

    return df

In [200]:
def handle_football_missing_values(df):
    """
    Function Description:
    Removes football rows missing essential match identifiers.

    Input:
    df (DataFrame): Football dataframe.

    Output:
    df (DataFrame): Football dataframe with unusable rows removed.
    """

#drops Nans as data becomes useless in the football data if the date, or teams do not exist
    df = df.dropna(
        subset=[
            "date",
            "hometeam",
            "awayteam"
        ]
    )

    return df

In [201]:
def filter_relevant_home_teams(df):
    """
    Function Description:
    Keeps only home matches involving teams mapped to the selected police forces.

    Input:
    df (DataFrame): Football dataframe containing hometeam column.

    Output:
    df (DataFrame): Filtered football dataframe for relevant home teams.
    """
    df = df.copy()

    relevant_teams = list(TEAM_FORCE_MAPPING.keys())

    df = df[df["hometeam"].isin(relevant_teams)]

    return df

In [202]:
def add_police_force_to_matches(df):
    """
    Function Description:
    Maps each home team to its corresponding police force.

    Input:
    df (DataFrame): Football dataframe containing hometeam column.

    Output:
    df (DataFrame): Football dataframe with police_force column added.
    """
    df = df.copy()

    df["police_force"] = df["hometeam"].map(
        TEAM_FORCE_MAPPING
    )

    return df

In [203]:
def create_match_count_column(df):
    """
    Function Description:
    Creates a match-count indicator so home matches can be aggregated by month.

    Input:
    df (DataFrame): Cleaned football dataframe.

    Output:
    df (DataFrame): Football dataframe with home_match_count column added.
    """
    df = df.copy()

    df["home_match_count"] = 1

    return df

In [204]:
def create_derby_column(df):
    """
    Function Description:
    Flags selected derby matches for event-based analysis.

    Input:
    df (DataFrame): Football dataframe containing hometeam and awayteam columns.

    Output:
    df (DataFrame): Football dataframe with derby_match_count column added.
    """
    df = df.copy()

#derby matches in the data we have
    derby_matches = [
        ("Liverpool", "Everton"),
        ("Arsenal", "Tottenham")
    ]

    df["derby_match_count"] = 0

    for team_a, team_b in derby_matches:
        derby_mask = (
            ((df["hometeam"] == team_a) & (df["awayteam"] == team_b)) |
            ((df["hometeam"] == team_b) & (df["awayteam"] == team_a))
        )

        df.loc[derby_mask, "derby_match_count"] = 1

    return df

In [205]:
def validate_reporting_grain_football(df):
    """
    Function Description:
    Checks whether the aggregated football dataset has duplicate rows at police force, year, and month level.

    Input:
    df (DataFrame): Aggregated football dataframe.

    Output:
    None: Prints duplicate count and validation message.
    """
    duplicates = df.duplicated(
        subset=[
            "police_force",
            "year",
            "month_num"
        ]
    ).sum()

    print("Duplicate reporting rows:", duplicates)

    if duplicates == 0:
        print("Reporting grain is valid.")
    else:
        print("There are duplicate rows.")

In [206]:
def process_football_file(file_path):
    """
    Function Description:
    Imports and cleans one football CSV file using the football cleaning pipeline.

    Input:
    file_path (str): Path to the football CSV file.

    Output:
    df (DataFrame): Cleaned football dataframe for one file.
    """
#imports files
    df = pd.read_csv(
        file_path,
        low_memory=False
    )
    original_df = df.copy()
    
    df = clean_football_columns(df)
    df = select_football_columns(df)
    df = clean_football_dates(df)
    df = handle_football_missing_values(df)
    df = filter_relevant_home_teams(df)
    df = add_police_force_to_matches(df)
    df = create_match_count_column(df)
    df = create_derby_column(df)

    print_size_change(
    file_path,
    original_df,
    df
    )

    return df

In [207]:
def process_football_files(football_files):
    """
    Function Description:
    Processes multiple football CSV files and combines them into one cleaned dataframe.

    Input:
    football_files (list): List of football CSV file paths.

    Output:
    football_clean (DataFrame): Combined cleaned football dataframe.
    """
    cleaned_files = []

    for file_path in football_files:
        cleaned_df = process_football_file(file_path)
        cleaned_files.append(cleaned_df)

    football_clean = pd.concat(
        cleaned_files,
        ignore_index=True
    )

    return football_clean

In [208]:
#csv football files
football_files = [
    "Prem-18-19.csv",
    "Prem-19-20.csv",
    "Prem-20-21.csv",
    "Prem-21-22.csv",
    "Prem-22-23.csv",
    "Prem-23-24.csv",
    "Prem-24-25.csv"
]

In [209]:
#uses functions above to import and clean the football data
football_clean = process_football_files(
    football_files
)

Prem-18-19.csv
Original rows: 380
Final rows: 171
Rows removed: 209

Prem-19-20.csv
Original rows: 380
Final rows: 190
Rows removed: 190

Prem-20-21.csv
Original rows: 380
Final rows: 190
Rows removed: 190

Prem-21-22.csv
Original rows: 380
Final rows: 190
Rows removed: 190

Prem-22-23.csv
Original rows: 380
Final rows: 190
Rows removed: 190

Prem-23-24.csv
Original rows: 380
Final rows: 190
Rows removed: 190

Prem-24-25.csv
Original rows: 380
Final rows: 190
Rows removed: 190

In [210]:
football_clean

,date,hometeam,awayteam,fthg,ftag,ftr,year,month_num,month_name,police_force,home_match_count,derby_match_count
0,2018-08-11,Newcastle,Tottenham,1,2,A,2018,8,August,Northumbria Police,1,0
1,2018-08-11,Wolves,Everton,2,2,D,2018,8,August,West Midlands Police,1,0
2,2018-08-12,Arsenal,Man City,0,2,A,2018,8,August,Metropolitan Police,1,0
3,2018-08-12,Liverpool,West Ham,4,0,H,2018,8,August,Merseyside Police,1,0
4,2018-08-18,Chelsea,Arsenal,3,2,H,2018,8,August,Metropolitan Police,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1306,2025-05-20,Crystal Palace,Wolves,4,2,H,2025,5,May,Metropolitan Police,1,0
1307,2025-05-25,Liverpool,Crystal Palace,1,1,D,2025,5,May,Merseyside Police,1,0
1308,2025-05-25,Newcastle,Everton,0,1,A,2025,5,May,Northumbria Police,1,0
1309,2025-05-25,Tottenham,Brighton,1,4,A,2025,5,May,Metropolitan Police,1,0
1310,2025-05-25,Wolves,Brentford,1,1,D,2025,5,May,West Midlands Police,1,0

In [211]:
def aggregate_football_monthly(
    df,
    output_file
):
    """
    Function Description:
    Aggregates cleaned football data to police force and month level, validates it, checks missing values, and exports it.

    Input:
    df (DataFrame): Cleaned football dataframe.
    output_file (str): Output CSV filename or path.

    Output:
    football_monthly (DataFrame): Aggregated football dataframe.
    """

    football_monthly = (
        df.groupby(
            [
                "police_force",
                "year",
                "month_num",
                "month_name"
            ],
            as_index=False
        )
        .agg({
            "home_match_count": "sum",
            "derby_match_count": "sum"
        })
    )
#validates data
    validate_reporting_grain_football(football_monthly)
    
#checks for missing values
    check_missing_values(football_monthly)

#creates a csv file for the cleaned football data
    football_monthly.to_csv(
        output_file,
        index=False
    )

    print(f"Exported: {output_file}")

    return football_monthly

In [212]:
football_monthly = (
    aggregate_football_monthly(
        football_clean,
        "football_monthly.csv"
    )
)

Duplicate reporting rows: 0
Reporting grain is valid.
police_force         0
year                 0
month_num            0
month_name           0
home_match_count     0
derby_match_count    0
dtype: int64
Exported: football_monthly.csv

In [213]:
def merge_crime_and_football(
    crime_df,
    football_df
):
    """
    Function Description:
    Merges monthly crime data with monthly football activity data.

    Input:
    crime_df (DataFrame): Monthly aggregated crime dataframe.
    football_df (DataFrame): Monthly aggregated football dataframe.

    Output:
    final_df (DataFrame): Crime dataframe enriched with football match metrics.
    """

#left merge on football data
    final_df = crime_df.merge(
        football_df,
        on=[
            "police_force",
            "year",
            "month_num",
            "month_name"
        ],
        how="left"
    )

# Replace missing football values with 0
    final_df["home_match_count"] = (
        final_df["home_match_count"]
        .fillna(0)
        .astype(int)
    )

    final_df["derby_match_count"] = (
        final_df["derby_match_count"]
        .fillna(0)
        .astype(int)
    )

#validating dataframe
    duplicates = final_df.duplicated(
        subset=[
            "police_force",
            "year",
            "month_num",
            "crime_type"
        ]
    ).sum()

    print(
        f"Duplicate rows: {duplicates}"
    )

#checks for missing values
    check_missing_values(final_df)

    return final_df

In [214]:
#using functions above to merge the crime and football dataframes
crime_football_df = (
    merge_crime_and_football(
        crime_monthly,
        football_monthly
    )
)

Duplicate rows: 0
police_force         0
date                 0
year                 0
month_num            0
month_name           0
crime_type           0
crime_count          0
home_match_count     0
derby_match_count    0
dtype: int64

In [215]:
crime_football_df

,police_force,date,year,month_num,month_name,crime_type,crime_count,home_match_count,derby_match_count
0,Merseyside Police,2019-04-01,2019,4,April,Anti-social behaviour,2534,4,0
1,Merseyside Police,2019-04-01,2019,4,April,Bicycle theft,136,4,0
2,Merseyside Police,2019-04-01,2019,4,April,Burglary,716,4,0
3,Merseyside Police,2019-04-01,2019,4,April,Criminal damage and arson,1289,4,0
4,Merseyside Police,2019-04-01,2019,4,April,Drugs,764,4,0
...,...,...,...,...,...,...,...,...,...
4013,West Midlands Police,2025-03-01,2025,3,March,Robbery,475,1,0
4014,West Midlands Police,2025-03-01,2025,3,March,Shoplifting,3003,1,0
4015,West Midlands Police,2025-03-01,2025,3,March,Theft from the person,201,1,0
4016,West Midlands Police,2025-03-01,2025,3,March,Vehicle crime,2213,1,0
4017,West Midlands Police,2025-03-01,2025,3,March,Violence and sexual offences,11263,1,0

In [216]:
def load_population_data(file_path):
    """
    Function Description:
    Imports the population CSV file using the correct header row.

    Input:
    file_path (str): Path to the population CSV file.

    Output:
    df (DataFrame): Raw population dataframe.
    """
#imports csv
    df = pd.read_csv(
        file_path,
        header=1
    )

    return df

In [217]:
def clean_population_columns(df):
    """
    Function Description:
    Standardises population dataset column names.

    Input:
    df (DataFrame): Raw population dataframe.

    Output:
    df (DataFrame): Population dataframe with cleaned column names.
    """
    df = df.copy()

    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
    )

    return df

In [218]:
def select_population_columns(df):
    """
    Function Description:
    Keeps only the local authority name and yearly population columns required for the project.

    Input:
    df (DataFrame): Raw population dataframe.

    Output:
    df (DataFrame): Reduced population dataframe.
    """
#columns we need in the population data
    required_columns = [
        "laname23",
        "population_2019",
        "population_2020",
        "population_2021",
        "population_2022",
        "population_2023",
        "population_2024"
    ]

    df = df[required_columns]

    return df

In [219]:
#used to correlate the area with the police force
POLICE_FORCE_AREAS = {
    "Metropolitan Police": [
        "Barking and Dagenham", "Barnet", "Bexley", "Brent", "Bromley",
        "Camden", "Croydon", "Ealing", "Enfield", "Greenwich",
        "Hackney", "Hammersmith and Fulham", "Haringey", "Harrow",
        "Havering", "Hillingdon", "Hounslow", "Islington",
        "Kensington and Chelsea", "Kingston upon Thames", "Lambeth",
        "Lewisham", "Merton", "Newham", "Redbridge",
        "Richmond upon Thames", "Southwark", "Sutton",
        "Tower Hamlets", "Waltham Forest", "Wandsworth",
        "Westminster", "City of London"
    ],

    "Merseyside Police": [
        "Liverpool", "Knowsley", "Sefton", "St. Helens", "Wirral"
    ],

    "West Midlands Police": [
        "Birmingham", "Coventry", "Dudley", "Sandwell",
        "Solihull", "Walsall", "Wolverhampton"
    ],

    "Northumbria Police": [
        "Newcastle upon Tyne", "Gateshead", "North Tyneside",
        "South Tyneside", "Sunderland", "Northumberland"
    ]
}

In [220]:
def add_police_force_from_local_authority(df):
    """
    Function Description:
    Maps local authorities to the police forces used in the project and removes unmapped areas.

    Input:
    df (DataFrame): Population dataframe at local-authority level.

    Output:
    df (DataFrame): Population dataframe with police_force column added.
    """
    df = df.copy()

    area_to_force = {}

    for force, areas in POLICE_FORCE_AREAS.items():
        for area in areas:
            area_to_force[area] = force

    df["police_force"] = df["laname23"].map(area_to_force)

    df = df.dropna(subset=["police_force"])

    return df

In [221]:
def reshape_population_data(df):
    """
    Function Description:
    Converts population data from wide format to long format so each row represents one police force and year.

    Input:
    df (DataFrame): Population dataframe with one population column per year.

    Output:
    population_long (DataFrame): Long-format population dataframe with year and population columns.
    """
    population_long = df.melt(
        id_vars="police_force",
        value_vars=[
            "population_2019",
            "population_2020",
            "population_2021",
            "population_2022",
            "population_2023",
            "population_2024"
        ],
        var_name="year",
        value_name="population"
    )

    return population_long

In [222]:
def clean_population_year(df):
    """
    Function Description:
    Converts population year labels into integer year values.

    Input:
    df (DataFrame): Long-format population dataframe with year labels.

    Output:
    df (DataFrame): Population dataframe with numeric year column.
    """
    df = df.copy()

    df["year"] = (
        df["year"]
        .str.replace("population_", "")
        .astype(int)
    )

    return df

In [223]:
def clean_population_values(df):
    """
    Function Description:
    Converts population values to integers after removing commas.

    Input:
    df (DataFrame): Population dataframe containing population values.

    Output:
    df (DataFrame): Population dataframe with numeric population column.
    """
    df = df.copy()

    df["population"] = (
        df["population"]
        .astype(str)
        .str.replace(",", "")
        .astype(int)
    )

    return df

In [224]:
def validate_population_data(df):
    """
    Function Description:
    Validates population data by checking duplicates, missing values, and police force counts.

    Input:
    df (DataFrame): Population dataframe to validate.

    Output:
    None: Prints validation summary.
    """
    duplicates = df.duplicated(
        subset=[
            "police_force",
            "year"
        ]
    ).sum()

    print("Duplicate rows:", duplicates)

    print("\nMissing values:")
    print(df.isna().sum())

    print("\nPolice forces:")
    print(df["police_force"].value_counts())

In [225]:
def export_population_data(df, output_file):
    """
    Function Description:
    Exports the cleaned population dataframe to CSV.

    Input:
    df (DataFrame): Population dataframe to export.
    output_file (str): Output CSV filename or path.

    Output:
    None: Exports CSV file and prints confirmation.
    """
#exporting csv file of population dataframe
    df.to_csv(
        output_file,
        index=False
    )

    print(f"Exported: {output_file}")

In [226]:
def aggregate_population_by_force(df):
    """
    Function Description:
    Aggregates local-authority population values to police-force and year level.

    Input:
    df (DataFrame): Population dataframe at local-authority/year level.

    Output:
    population_by_force (DataFrame): Population dataframe aggregated to police-force/year level.
    """

#aggregating population data
    population_by_force = (
        df.groupby(
            ["police_force", "year"],
            as_index=False
        )
        .agg(
            population=("population", "sum")
        )
    )

    return population_by_force

In [227]:
def add_2025_population(df):
    """
    Function Description:
    Creates 2025 population rows by reusing 2024 values as proxy estimates.

    Input:
    df (DataFrame): Population dataframe containing 2024 rows.

    Output:
    df (DataFrame): Population dataframe with 2025 rows added.
    """

#creating 2025 population column
    population_2025 = (
        df[df["year"] == 2024]
        .copy()
    )

    population_2025["year"] = 2025

#adding the column to the datafarme
    df = pd.concat(
        [df, population_2025],
        ignore_index=True
    )

    return df

In [228]:
def process_population_data(file_path, output_file):
    """
    Function Description:
    Runs the full population pipeline: import, clean, map areas, reshape, clean values, validate, aggregate, add 2025, and export.

    Input:
    file_path (str): Path to population CSV file.
    output_file (str): Output CSV filename or path.

    Output:
    df (DataFrame): Cleaned and aggregated population dataframe.
    """
    df = load_population_data(file_path)

    df = clean_population_columns(df)

    df = select_population_columns(df)

    df = add_police_force_from_local_authority(df)

    df = reshape_population_data(df)

    df = clean_population_year(df)

    df = clean_population_values(df)

    validate_population_data(df)

    df = aggregate_population_by_force(df)

    df = add_2025_population(df)

    export_population_data(
        df,
        output_file
    )

    return df

In [229]:
#using functions above to import the population data and clean it
population_clean = process_population_data(
    "myebtablesenglandwales20112024(MYEB3).csv",
    "population_clean.csv"
)

Duplicate rows: 282

Missing values:
police_force    0
year            0
population      0
dtype: int64

Police forces:
police_force
Metropolitan Police     198
West Midlands Police     42
Northumbria Police       36
Merseyside Police        30
Name: count, dtype: int64
Exported: population_clean.csv

In [230]:
population_clean

            police_force  year  population
0      Merseyside Police  2019     1417661
1      Merseyside Police  2020     1417728
2      Merseyside Police  2021     1423718
3      Merseyside Police  2022     1439842
4      Merseyside Police  2023     1459120
5      Merseyside Police  2024     1475541
6    Metropolitan Police  2019     8889743
7    Metropolitan Police  2020     8867008
8    Metropolitan Police  2021     8804769
9    Metropolitan Police  2022     8871368
10   Metropolitan Police  2023     8999705
11   Metropolitan Police  2024     9089736
12    Northumbria Police  2019     1443488
13    Northumbria Police  2020     1443775
14    Northumbria Police  2021     1447681
15    Northumbria Police  2022     1465884
16    Northumbria Police  2023     1488419
17    Northumbria Police  2024     1509809
18  West Midlands Police  2019     2921091
19  West Midlands Police  2020     2921476
20  West Midlands Police  2021     2918251
21  West Midlands Police  2022     2949985
22  West Midlands Police  2023     2994216
23  West Midlands Police  2024     3036605
24     Merseyside Police  2025     1475541
25   Metropolitan Police  2025     9089736
26    Northumbria Police  2025     1509809
27  West Midlands Police  2025     3036605

In [231]:
def merge_population(main_df, population_df):
    """
    Function Description:
    Merges population estimates into the crime and football dataset.

    Input:
    main_df (DataFrame): Crime and football dataset.
    population_df (DataFrame): Population dataframe at police-force/year level.

    Output:
    merged_df (DataFrame): Dataset enriched with population data.
    """

#left merge on population
    merged_df = main_df.merge(
        population_df,
        on=[
            "police_force",
            "year"
        ],
        how="left"
    )

    return merged_df

In [232]:
#using functions above to merge crime/football dataframe and the population dataframe
final_df = merge_population(
    crime_football_df,
    population_clean
)

In [233]:
final_df

,police_force,date,year,month_num,month_name,crime_type,crime_count,home_match_count,derby_match_count,population
0,Merseyside Police,2019-04-01,2019,4,April,Anti-social behaviour,2534,4,0,1417661
1,Merseyside Police,2019-04-01,2019,4,April,Bicycle theft,136,4,0,1417661
2,Merseyside Police,2019-04-01,2019,4,April,Burglary,716,4,0,1417661
3,Merseyside Police,2019-04-01,2019,4,April,Criminal damage and arson,1289,4,0,1417661
4,Merseyside Police,2019-04-01,2019,4,April,Drugs,764,4,0,1417661
...,...,...,...,...,...,...,...,...,...,...
4013,West Midlands Police,2025-03-01,2025,3,March,Robbery,475,1,0,3036605
4014,West Midlands Police,2025-03-01,2025,3,March,Shoplifting,3003,1,0,3036605
4015,West Midlands Police,2025-03-01,2025,3,March,Theft from the person,201,1,0,3036605
4016,West Midlands Police,2025-03-01,2025,3,March,Vehicle crime,2213,1,0,3036605
4017,West Midlands Police,2025-03-01,2025,3,March,Violence and sexual offences,11263,1,0,3036605

In [234]:
def add_crime_rate(df):
    """
    Function Description:
    Creates a crime rate per 1,000 residents using crime count and population.

    Input:
    df (DataFrame): Final merged analytical dataframe.

    Output:
    df (DataFrame): Dataframe with crime_rate_per_1000 column added.
    """

    df = df.copy()

#creating a crime rate column
    df["crime_rate_per_1000"] = (
        df["crime_count"] / df["population"]
    ) * 1000

    return df

In [235]:
final_df = add_crime_rate(final_df)

In [236]:
final_df

,police_force,date,year,month_num,month_name,crime_type,crime_count,home_match_count,derby_match_count,population,crime_rate_per_1000
0,Merseyside Police,2019-04-01,2019,4,April,Anti-social behaviour,2534,4,0,1417661,1.787451
1,Merseyside Police,2019-04-01,2019,4,April,Bicycle theft,136,4,0,1417661,0.095933
2,Merseyside Police,2019-04-01,2019,4,April,Burglary,716,4,0,1417661,0.505057
3,Merseyside Police,2019-04-01,2019,4,April,Criminal damage and arson,1289,4,0,1417661,0.909244
4,Merseyside Police,2019-04-01,2019,4,April,Drugs,764,4,0,1417661,0.538916
...,...,...,...,...,...,...,...,...,...,...,...
4013,West Midlands Police,2025-03-01,2025,3,March,Robbery,475,1,0,3036605,0.156425
4014,West Midlands Police,2025-03-01,2025,3,March,Shoplifting,3003,1,0,3036605,0.988933
4015,West Midlands Police,2025-03-01,2025,3,March,Theft from the person,201,1,0,3036605,0.066192
4016,West Midlands Police,2025-03-01,2025,3,March,Vehicle crime,2213,1,0,3036605,0.728774
4017,West Midlands Police,2025-03-01,2025,3,March,Violence and sexual offences,11263,1,0,3036605,3.709076

In [237]:
def validate_final_dataset(df):
    """
    Function Description:
    Runs final validation checks on the reporting dataset.

    Input:
    df (DataFrame): Final reporting dataframe.

    Output:
    None: Prints row count, columns, missing values, duplicate checks, police force counts, crime type counts, and date range.
    """

    print("Rows:", len(df))
    print("Columns:", df.shape[1])

    print("\nMissing values:")
    print(df.isna().sum())

    duplicates = df.duplicated(
        subset=[
            "police_force",
            "year",
            "month_num",
            "crime_type"
        ]
    ).sum()

    print("\nDuplicate reporting rows:", duplicates)

    print("\nPolice forces:")
    print(df["police_force"].value_counts())

    print("\nCrime types:")
    print(df["crime_type"].value_counts())

    print("\nDate range:")
    print(df["year"].min(), "to", df["year"].max())

In [238]:
validate_final_dataset(final_df)

Rows: 4018
Columns: 11

Missing values:
police_force           0
date                   0
year                   0
month_num              0
month_name             0
crime_type             0
crime_count            0
home_match_count       0
derby_match_count      0
population             0
crime_rate_per_1000    0
dtype: int64

Duplicate reporting rows: 0

Police forces:
police_force
Merseyside Police       1008
Metropolitan Police     1008
Northumbria Police      1008
West Midlands Police     994
Name: count, dtype: int64

Crime types:
crime_type
Anti-social behaviour           287
Bicycle theft                   287
Burglary                        287
Criminal damage and arson       287
Drugs                           287
Other crime                     287
Other theft                     287
Possession of weapons           287
Public order                    287
Robbery                         287
Shoplifting                     287
Theft from the person           287
Vehicle crime                   287
Violence and sexual offences    287
Name: count, dtype: int64

Date range:
2019 to 2025

To explain the numbers: west midlands police has 14 less than the others as March of 2022 has no data for west midlands.

In [239]:
final_df.to_csv("final_reporting_dataset.csv", index=False)